apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  labels:
    app: product-service
data:
  APP_NAME: "product-service"
  ENV: "dev"
  PORT: "8080"
  LOG_LEVEL: "info"
  CACHE_TTL: "300"
